//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UPC.PichangaApp.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class reserva
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public reserva()
        {
            this.reserva_detalle = new HashSet<reserva_detalle>();
        }
    
        public int id_reserva { get; set; }
        public int id_cliente { get; set; }
        public int id_horario { get; set; }
        public System.DateTime fecha_registro { get; set; }
        public int cantidad_disponible { get; set; }
        public bool activo { get; set; }
    
        public virtual cliente cliente { get; set; }
        public virtual horario horario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<reserva_detalle> reserva_detalle { get; set; }
    }
}
